registration:
  image: registration-service
  ports: 
    - "3000:4000"
  expose: 
    - "4000"
  links:
    - "account:account-service"
  environment:
    RACK_PORT: 4000
    RACK_ENV: development

account:
  image: account-service
  ports:
    - "3001:4001"
  expose: 
    - "4001"
  environment:
    RACK_PORT: 4001
    RACK_ENV: development