source 'https://rubygems.org'

gem 'rake', '~> 10.4.2'
gem 'sinatra', '~> 1.4.7'
gem 'thin', '~> 1.6.4'
gem 'mail', '~> 2.6.4'
gem 'bunny', '~> 2.5'

group :development do
  gem 'rerun', '~> 0.11.0'
end

group :test do
  gem 'rspec', '~> 3.4.0'
  gem 'httparty', '~> 0.13.7'
  gem 'pact', '~> 1.9.0'
end