version: '2'

services:

  logspout:
    image: gliderlabs/logspout
    container_name: logspout
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: syslog+tls://logs4.papertrailapp.com:10242

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  registration-service:
    image: registration-service
    ports: 
      - "8080"
    environment:
      VIRTUAL_HOST: registration-service
      XENVIRONMENT: development
      RACK_PORT: 8080
      RACK_ENV: production

  account-service:
    image: account-service
    ports:
      - "8080"
    environment:
      VIRTUAL_HOST: account-service
      XENVIRONMENT: development
      RACK_PORT: 8080
      RACK_ENV: production

  email-service:
    image: email-service
    ports:
      - "8080"
    environment:
      VIRTUAL_HOST: email-service
      XENVIRONMENT: development
      RACK_PORT: 8080
      RACK_ENV: production